function createfigure(xvector1, yvector1)
%CREATEFIGURE(XVECTOR1, YVECTOR1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 26-Jan-2017 17:30:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(xvector1,yvector1,'FaceColor',[0 0 0],'BarWidth',1);

% Create xlabel
xlabel({'Time to collision (s)'},'FontSize',18);

% Create title
title('G25-072416-01 - ITI: 45s');

% Create ylabel
ylabel({'Firing Frequency (Hz)'},'FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 90]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XTick',[-1 -0.5 0 0.5 1],'YTick',[0 30 60 90 120]);
